import type { LessonQuizItem } from "@/data/lessonContent/types";
import type { LessonMediaHints } from "@/data/lessonContent/types";
import type { LessonPedagogyExtras } from "@/data/lessonPedagogy.types";

function q(
  question: string,
  correctIndex: 0 | 1 | 2 | 3,
  a: string,
  b: string,
  c: string,
  d: string
): LessonQuizItem {
  return { question, correctIndex, options: [a, b, c, d] as const };
}

const MEDIA_STANDARD: LessonMediaHints = {
  needsVideo: true,
  needsImage: true,
  needsInfographic: true,
  needsSupportMaterial: true
};

const MEDIA_INTRO: LessonMediaHints = {
  needsVideo: true,
  needsImage: false,
  needsInfographic: true,
  needsSupportMaterial: true
};

/** Parágrafos didáticos — Markdown limitado (títulos/listas via quebras de linha; intro usa whitespace-pre-line na UI). */
export type Cannabis101LessonBody = {
  introduction: string;
  body: string;
  objectives: readonly string[];
  closingSummary: string;
  quiz: readonly LessonQuizItem[];
  professorNotes: string;
  media: LessonMediaHints;
  /** Texto da experiência stream — briefing, checkpoints, tom de sala THCProce. */
  pedagogy?: LessonPedagogyExtras;
};

/** Fonte canónica do texto das aulas Cannabis 101 no painel do campus: `lessonBodies` → `lessons.ts` → `getLessonRichContent`. Moodle/embed não alimenta este painel. */

/** Nota institucional única — substitui o parágrafo longo repetido em todas as aulas. */
const FOOTNOTE_MATERIALS =
  "Nota institucional: vídeos completos, PDFs e provas com validade formal ficam na sala digital THCProce; neste painel mantemos texto denso para estudo rápido no campus.";

export const CANNABIS101_LESSON_BODIES: Record<string, Cannabis101LessonBody> = {
  "c101-l01-boas-vindas": {
    introduction: [
      "# Boas-vindas e Introdução",
      "",
      "Olá, seja muito bem-vindo ao curso **CANNABIS 101 – Cultivo Medicinal e Recreativo**.",
      "Meu nome é **Sérgio Delvair da Costa**, fundador do projeto **THCProce**, e estou muito feliz em ter você aqui nesta jornada de aprendizado, consciência e evolução através do cultivo da cannabis.",
      "---",
      "# Sobre o Professor",
      "## Histórico Pessoal e Profissional",
      "Nasci em Goiânia, Goiás – Brasil, e atualmente resido na Califórnia, Estados Unidos, onde acompanho de perto a evolução da cannabis em um ambiente regulamentado e descriminalizado.",
      "Tenho mais de 40 anos de convivência com a cannabis e mais de 20 anos de experiência prática no cultivo da planta.",
      "Ao longo dessa caminhada, desenvolvi conhecimentos relacionados a:",
      "* cultivo medicinal e recreativo;",
      "* cultivo indoor e outdoor;",
      "* genética;",
      "* secagem e cura;",
      "* extrações;",
      "* redução de danos;",
      "* autonomia no cultivo;",
      "* e educação canábica.",
      "Também realizei diversos cursos e certificações nos Estados Unidos voltados ao cultivo e manejo profissional da cannabis.",
      "---",
      "# Experiência e Ativismo",
      "Minha trajetória vai além do cultivo.",
      "Sou ativista da cannabis há muitos anos e, no Brasil, fui preso por cultivar cannabis para consumo próprio, buscando justamente evitar o contato com o tráfico e promover autonomia ao usuário.",
      "Essa experiência marcou profundamente minha vida e fortaleceu ainda mais minha missão de ensinar, conscientizar e ajudar outras pessoas a compreenderem a cannabis de maneira responsável.",
      "Foi dessa caminhada que nasceu o projeto **THCProce**, canal e plataforma educacional criada para compartilhar conhecimento técnico, experiências reais e educação sobre cultivo de cannabis.",
      "---",
      "# Filosofia do THCProce",
      "Acreditamos que conhecimento transforma vidas.",
      "Nosso objetivo é ensinar pessoas comuns a compreenderem a cannabis:",
      "* como planta;",
      "* como ferramenta medicinal;",
      "* como cultura;",
      "* e como forma de autonomia pessoal.",
      "Aqui defendemos:",
      "* cultivo consciente;",
      "* redução de danos;",
      "* autocuidado;",
      "* responsabilidade;",
      "* e informação de qualidade.",
      "A filosofia central deste curso é simples:",
      "# Plantar para não comprar.",
      "---",
      "# Objetivos do Curso",
      "Este curso possui finalidade exclusivamente educacional e informativa.",
      "Nosso foco é ensinar:",
      "* cultivo responsável;",
      "* técnicas modernas e sustentáveis;",
      "* princípios científicos aplicados ao cultivo;",
      "* e conhecimentos voltados ao usuário pessoal previsto no Artigo 28 da legislação brasileira.",
      "Não incentivamos comércio ilegal ou práticas ilícitas.",
      "O objetivo é promover educação, consciência e conhecimento técnico sobre a cannabis.",
      "Ao longo das aulas, você aprenderá:",
      "* como iniciar um cultivo;",
      "* como escolher sementes;",
      "* preparação do ambiente;",
      "* iluminação;",
      "* nutrição;",
      "* irrigação;",
      "* identificação de problemas;",
      "* flora;",
      "* colheita;",
      "* secagem;",
      "* cura;",
      "* e muitos outros conhecimentos fundamentais.",
      "---",
      "# Metodologia de Ensino",
      "Minha metodologia é baseada em:",
      "* experiência prática real;",
      "* observação da planta;",
      "* técnicas modernas;",
      "* linguagem acessível;",
      "* e aplicação prática do conhecimento.",
      "O objetivo não é apenas mostrar teorias, mas ensinar você a realmente compreender o cultivo no dia a dia.",
      "Mesmo pessoas sem experiência poderão acompanhar o curso e evoluir passo a passo.",
      "---",
      "# Interatividade e Suporte",
      "Valorizamos muito a troca de experiências entre alunos e cultivadores.",
      "Durante o curso, buscaremos criar uma comunidade baseada em:",
      "* respeito;",
      "* aprendizado;",
      "* empatia;",
      "* e evolução coletiva.",
      "Dúvidas, perguntas e interações fazem parte do processo de aprendizado.",
      "---",
      "# Uma Visão para o Futuro",
      "Estamos vivendo um momento histórico de transformação cultural em relação à cannabis.",
      "Cada vez mais pessoas no mundo compreendem:",
      "* os benefícios terapêuticos da planta;",
      "* a importância da regulamentação;",
      "* e a necessidade de superar antigos preconceitos.",
      "Minha missão é contribuir para um futuro onde o cultivo consciente e o uso responsável da cannabis sejam tratados com maturidade, ciência e humanidade.",
      "---",
      "# Seja Bem-vindo ao THCProce Campus",
      "Muito obrigado pela sua presença aqui.",
      "Espero sinceramente que este curso ajude você a desenvolver conhecimento, autonomia e consciência.",
      "Prepare-se para muitas aulas, muito aprendizado e uma verdadeira imersão no universo do cultivo de cannabis.",
      "Vamos cultivar conhecimento juntos."
    ].join("\n"),
    /** Narrativa principal está no `introduction`; evita duplicar voz ou checklist antiga. */
    body: "",
    objectives: [
      "Reconhecer a missão do THCProce: educação, cultivo consciente, redução de danos e autonomia pessoal, sem comércio ilegal.",
      "Compreender os objetivos educacionais do CANNABIS 101 e o enquadramento referencial ao usuário pessoal (Art. 28), em tom informativo e não jurídico.",
      "Conhecer a metodologia da trilha — experiência prática, linguagem acessível e aplicação no dia a dia do cultivador."
    ],
    closingSummary:
      "A próxima aula percorre a história e as origens da cannabis — da Ásia Central à proibição e ao retorno da ciência. Avance quando quiser.",
    quiz: [
      q(
        "Segundo esta abertura, qual é a finalidade declarada do CANNABIS 101?",
        1,
        "Orientação jurídica individual e defesa em processo",
        "Exclusivamente educação e informação, sem incentivar comércio ilegal",
        "Garantia de autorização para cultivo comercial em qualquer país",
        "Substituição de receita médica por conteúdo online"
      ),
      q(
        "A filosofia central citada na apresentação do THCProce é:",
        2,
        "Comprar flores prontas para garantir acesso",
        "Delegar todo o cultivo a terceiros sem aprender",
        "Plantar para não comprar — autonomia e cultivo consciente",
        "Ignorar a legislação local sempre que conveniente"
      ),
      q(
        "Sobre a metodologia deste curso, o que o professor prioriza?",
        3,
        "Somente teoria abstrata, sem observação da planta",
        "Equipamentos caros como pré-requisito obrigatório",
        "Velocidade de conclusão com abertura de todas as aulas de uma vez",
        "Experiência prática, observação da planta e linguagem acessível ao dia a dia"
      )
    ],
    professorNotes:
      "Boas-vindas presenciais: ambiente acolhedor; dúvidas sobre cultivo responsável são bem-vindas. Canal paralelo para materiais formais permanece a sala digital THCProce.",
    media: MEDIA_INTRO
  },

  "c101-l02-o-que-e-cannabis": {
    introduction: [
      "# História e Origens da Cannabis",
      "",
      "## Dos rituais ancestrais à ciência moderna — conheça a jornada milenar da planta mais versátil do mundo",
      "",
      "⏰ 12 min de vídeo",
      "📖 10 min de leitura",
      "🎯 Nível: Iniciante",
      "",
      "## Cannabis: uma relação de mais de 10 mil anos com a humanidade",
      "",
      "A cannabis é uma das plantas mais antigas cultivadas pelo ser humano.",
      "",
      "Muito antes da escrita, dos impérios modernos e das religiões organizadas, a cannabis já acompanhava a humanidade como:",
      "",
      "- alimento;",
      "- fibra;",
      "- medicamento;",
      "- óleo;",
      "- tecido;",
      "- papel;",
      "- ferramenta espiritual;",
      "- e planta medicinal.",
      "",
      "Sua história se mistura diretamente com a própria evolução da civilização humana.",
      "",
      "Ao longo de milhares de anos, povos antigos aprenderam a utilizar praticamente todas as partes da planta:",
      "",
      "- sementes;",
      "- folhas;",
      "- flores;",
      "- fibras;",
      "- raízes;",
      "- e resinas.",
      "",
      "Poucas plantas tiveram uma importância tão ampla na história da humanidade.",
      "",
      "## Nesta aula, você vai entender:",
      "",
      "- onde a cannabis surgiu;",
      "- como ela se espalhou pelo mundo;",
      "- por que diferentes civilizações consideravam essa planta sagrada;",
      "- como ela foi proibida;",
      "- e por que hoje a ciência moderna voltou a estudar seus efeitos medicinais."
    ].join("\n"),
    body: [
      "## Origem da Cannabis — Ásia Central",
      "",
      "Os primeiros registros arqueológicos relacionados à cannabis foram encontrados na região da Ásia Central, principalmente em áreas que hoje pertencem:",
      "",
      "- ao Cazaquistão;",
      "- Mongólia;",
      "- oeste da China;",
      "- e regiões montanhosas próximas ao Himalaia.",
      "",
      "Vestígios de sementes carbonizadas e fibras de cânhamo indicam que a planta já era utilizada há mais de 10 mil anos.",
      "",
      "A cannabis se desenvolveu naturalmente em regiões de:",
      "",
      "- clima seco;",
      "- grande exposição solar;",
      "- noites frias;",
      "- e altitudes elevadas.",
      "",
      "Essas condições ajudaram a moldar a resistência e adaptabilidade da planta.",
      "",
      "Com o passar do tempo, povos nômades começaram a transportar sementes durante suas migrações, espalhando a cannabis lentamente por diversos continentes.",
      "",
      "## Cannabis na Medicina Chinesa",
      "",
      "Um dos registros medicinais mais antigos da humanidade envolvendo cannabis vem da China Antiga.",
      "",
      "Por volta de 2737 a.C., o imperador Shen Nung — considerado o pai da medicina chinesa — descreveu a cannabis em textos medicinais antigos.",
      "",
      "A planta era utilizada para auxiliar no tratamento de:",
      "",
      "- dores;",
      "- inflamações;",
      "- reumatismo;",
      "- malária;",
      "- problemas digestivos;",
      "- e distúrbios menstruais.",
      "",
      "Na medicina chinesa ancestral, a cannabis era considerada uma planta de equilíbrio.",
      "",
      "Mesmo milhares de anos atrás, os povos antigos já percebiam que a cannabis interagia diretamente com o corpo humano de maneira terapêutica.",
      "",
      "Hoje, sabemos que isso possui relação com o Sistema Endocanabinoide — descoberto pela ciência apenas em 1992.",
      "",
      "## Cannabis na Índia — Planta Sagrada",
      "",
      "Na Índia Antiga, a cannabis assumiu um papel profundamente espiritual.",
      "",
      "Os textos sagrados Vedas mencionavam o “bhang”, preparado tradicional feito com cannabis, leite e especiarias.",
      "",
      "A planta era utilizada:",
      "",
      "- em rituais religiosos;",
      "- cerimônias espirituais;",
      "- meditação;",
      "- festivais;",
      "- e práticas de expansão da consciência.",
      "",
      "Na tradição hindu, a cannabis é associada ao deus Shiva.",
      "",
      "Até hoje, algumas práticas religiosas indianas mantêm o uso ritualístico da planta.",
      "",
      "Enquanto no mundo moderno a cannabis passou a ser criminalizada em muitos lugares, em culturas antigas ela era vista como:",
      "",
      "- planta medicinal;",
      "- planta de sabedoria;",
      "- e ferramenta espiritual.",
      "",
      "## Oriente Médio, África e o Haxixe",
      "",
      "Com as rotas comerciais antigas, a cannabis chegou ao Oriente Médio e ao norte da África.",
      "",
      "Nessas regiões, desenvolveu-se o uso do haxixe — a resina concentrada da planta.",
      "",
      "Povos árabes e persas aperfeiçoaram técnicas tradicionais de separação da resina muito antes da tecnologia moderna de extração.",
      "",
      "A cannabis era utilizada:",
      "",
      "- medicinalmente;",
      "- em práticas culturais;",
      "- socialmente;",
      "- e como preparação terapêutica.",
      "",
      "Em várias regiões africanas, a planta também foi integrada à medicina popular e tradições locais.",
      "",
      "## Cannabis e o Cânhamo — A Planta que Moveu Navios",
      "",
      "Muito além do uso medicinal, a cannabis foi extremamente importante para o desenvolvimento econômico da humanidade.",
      "",
      "O cânhamo industrial produzido a partir da cannabis era utilizado para fabricar:",
      "",
      "- cordas;",
      "- velas de navios;",
      "- roupas;",
      "- tecidos;",
      "- papel;",
      "- redes;",
      "- e materiais resistentes.",
      "",
      "Durante séculos, praticamente todas as grandes embarcações utilizavam fibras de cânhamo.",
      "",
      "Sem o cânhamo, boa parte da navegação marítima mundial teria sido muito mais difícil.",
      "",
      "Muitos documentos históricos, mapas antigos e até papéis utilizados em governos foram produzidos utilizando fibras derivadas do cânhamo.",
      "",
      "## Cannabis no Brasil Colonial",
      "",
      "A cannabis chegou ao Brasil durante o período colonial através dos portugueses e também por influência de povos africanos escravizados.",
      "",
      "O cânhamo era considerado importante economicamente para:",
      "",
      "- produção de fibras;",
      "- cordas;",
      "- tecidos;",
      "- e materiais náuticos.",
      "",
      "Em algumas regiões do Brasil colonial, a Coroa Portuguesa incentivava o cultivo da planta.",
      "",
      "Existem registros históricos de estímulo oficial ao plantio de cânhamo.",
      "",
      "Além disso, muitos conhecimentos tradicionais sobre o uso da cannabis sobreviveram através das culturas afro-brasileiras.",
      "",
      "A palavra “maconha” possui origem africana, provavelmente derivada do quimbundo “ma’kanha”.",
      "",
      "## O Século XX e a Proibição",
      "",
      "Apesar de sua longa história medicinal e industrial, a cannabis passou a ser proibida em vários países durante o século XX.",
      "",
      "Nos Estados Unidos, a proibição ganhou força em 1937 com o Marihuana Tax Act.",
      "",
      "Diversos fatores contribuíram para isso:",
      "",
      "- interesses econômicos;",
      "- disputas industriais;",
      "- preconceitos sociais;",
      "- racismo;",
      "- campanhas políticas;",
      "- e desinformação.",
      "",
      "A cannabis passou a ser associada negativamente através de campanhas de medo.",
      "",
      "Esse período marcou o início da chamada “guerra às drogas”.",
      "",
      "A proibição impactou:",
      "",
      "- pesquisas científicas;",
      "- pacientes;",
      "- usuários medicinais;",
      "- cultivadores;",
      "- e diversas culturas relacionadas à planta.",
      "",
      "Mesmo assim, o uso da cannabis nunca deixou de existir.",
      "",
      "## A Ciência Moderna e o Retorno da Cannabis",
      "",
      "Em 1964, o cientista Raphael Mechoulam isolou o THC pela primeira vez.",
      "",
      "Décadas depois, em 1992, cientistas descobriram o Sistema Endocanabinoide — um sistema biológico presente no corpo humano responsável por equilíbrio e regulação de diversas funções.",
      "",
      "Essa descoberta revolucionou a compreensão científica da cannabis.",
      "",
      "Hoje sabemos que o corpo humano possui receptores específicos que interagem com os canabinoides da planta.",
      "",
      "Atualmente, pesquisas investigam aplicações terapêuticas da cannabis em:",
      "",
      "- dor crônica;",
      "- epilepsia;",
      "- ansiedade;",
      "- insônia;",
      "- náusea;",
      "- Parkinson;",
      "- autismo;",
      "- inflamações;",
      "- e diversas outras condições.",
      "",
      "A ciência moderna começou a confirmar muitos conhecimentos que povos ancestrais já utilizavam há milhares de anos.",
      "",
      "## Cannabis no Mundo Atual",
      "",
      "Nos últimos anos, diversos países passaram a rever suas políticas sobre cannabis.",
      "",
      "Hoje existem modelos de:",
      "",
      "- cannabis medicinal;",
      "- descriminalização;",
      "- cultivo pessoal;",
      "- redução de danos;",
      "- e regulamentação completa.",
      "",
      "A discussão global evolui rapidamente.",
      "",
      "No Brasil, o debate também cresce através:",
      "",
      "- da medicina;",
      "- do acesso ao CBD;",
      "- das associações;",
      "- das decisões judiciais;",
      "- e da busca por políticas mais humanas.",
      "",
      "## Você sabia?",
      "",
      "- A cannabis acompanha a humanidade há mais de 10 mil anos.",
      "- O cânhamo foi essencial para navegação marítima mundial.",
      "- O sistema endocanabinoide só foi descoberto em 1992.",
      "- Civilizações antigas já utilizavam cannabis medicinalmente muito antes da ciência moderna.",
      "- A palavra “maconha” possui provável origem africana.",
      "- O Brasil colonial incentivou o cultivo de cânhamo em determinados períodos históricos.",
      "",
      "## Linha do tempo",
      "",
      "- **~8000 a.C.** — Primeiros vestígios de uso da cannabis na Ásia Central.",
      "- **2737 a.C.** — Shen Nung registra usos medicinais da cannabis na China.",
      "- **1500 a.C.** — Textos Vedas na Índia mencionam cannabis como planta sagrada.",
      "- **~1000 a.C.** — Expansão para Oriente Médio e África.",
      "- **Século XVI** — Portugueses introduzem cânhamo no Brasil colonial.",
      "- **1937** — Marihuana Tax Act inicia a proibição nos EUA.",
      "- **1964** — Raphael Mechoulam isola o THC.",
      "- **1992** — Descoberta do Sistema Endocanabinoide.",
      "- **2020–2026** — Avanço global da regulamentação e da cannabis medicinal.",
      "",
      "### Depois desta aula, você compreende:",
      "",
      "- ✅ A origem geográfica da cannabis",
      "- ✅ Como a planta se espalhou pelo mundo",
      "- ✅ O papel histórico do cânhamo na civilização",
      "- ✅ Os usos medicinais e espirituais ancestrais",
      "- ✅ Como surgiu a proibição moderna",
      "- ✅ O impacto da guerra às drogas",
      "- ✅ O que é o Sistema Endocanabinoide",
      "- ✅ Por que a cannabis voltou ao centro das pesquisas científicas",
      "- ✅ Como a regulamentação está evoluindo no mundo moderno",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Localizar a origem arqueológica da cannabis na Ásia Central e os fatores ecológicos que moldaram a planta.",
      "Descrever rotas de dispersão — migrações, comércio, colonização — até o Brasil e outras regiões.",
      "Reconhecer usos ancestrais (China, Índia, Oriente Médio, África) e o sentido medicinal ou ritual conforme cada cultura.",
      "Explicar o papel econômico do cânhamo (cordas, velas, papel, tecidos) na expansão marítima e documental.",
      "Contextualizar a proibição do século XX, o Marihuana Tax Act (1937) e os efeitos da “guerra às drogas” sobre ciência e sociedade.",
      "Relacionar o isolamento do THC (Mechoulam, 1964), o sistema endocanabinoide (1992) e o retorno das pesquisas terapêuticas.",
      "Mapear tendências atuais de regulamentação e o debate no Brasil (medicina, CBD, associações, decisões judiciais)."
    ],
    closingSummary:
      "Você encerra esta aula com um arco claro: milênios de uso multifacetado, o peso do cânhamo na economia mundial, o corte confiscatório do século XX e a retomada científica que explica por que a planta voltou à agenda pública com dados, não só com estigma.",
    quiz: [
      q(
        "O Sistema Endocanabinoide foi descrito com evidência científica robusta em qual ano?",
        1,
        "1964 (ano do isolamento do THC)",
        "1992",
        "1937 (Marihuana Tax Act)",
        "2737 a.C. (registro atribuído a Shen Nung)"
      ),
      q(
        "Quem isolou o THC pela primeira vez, em 1964?",
        2,
        "Shen Nung",
        "Congresso dos EUA em 1937",
        "Raphael Mechoulam",
        "Charaka (textos ayurvédicos)"
      ),
      q(
        "Segundo o texto, o cânhamo industrial foi historicamente decisivo sobretudo para:",
        0,
        "Cordas, velas de navios, tecidos e papel — base da navegação e da documentação por séculos",
        "Substituir totalmente o comércio de especiarias no Índico",
        "Eliminar o uso ritual na Índia antiga",
        "Barrar migrações na Ásia Central"
      )
    ],
    professorNotes:
      "Sugestão: linha do tempo no quadro; contrastar cânhamo de fibra e usos psicoativos sem misturar julgamento moral com arquivo histórico. Reforçar que datas antigas (ex.: Shen Nung) são tradição escrita, não nota de laboratório.",
    media: MEDIA_STANDARD
  },

  "c101-l03-canhamo-maconha-medicinal": {
    introduction:
      "Cânhamo, maconha e cannabis medicinal brigam na política porque misturam botânica, lei e estigma — e cada um usa a mesma palavra pra mundos diferentes.\n\nAqui você vai trabalhar como analista de rótulo e categoria, não como manchete de capa.\n\nNorma muda: anota sempre a data em que você leu a fonte oficial.",
    body: [
      "OBJETIVO. Separar cadeias típicas de baixo THC (fibra, semente, cosméticos com limites), mercados informais de flores psicoativas e programas medicinais com prescrição e rastreabilidade.",
      "EXPLICAÇÃO. No Brasil, canabinoides prescritos seguem canais específicos (importação autorizada, registrados quando existirem). Decisões judiciais individuais criam camadas que mudam — cite sempre quando leu. Nos EUA, permissão estadual não apaga tensões federais em vários domínios.",
      "TABELA EM PROSA (três mundos).\n\nMundo A — Baixo THC industrial / alimentar / fibra: foco em limite legal de THC declarado e uso não psicoativo da matéria-prima.\n\nMundo B — Medicinal regulado: prescrição, rótulo com teores, farmácia ou canal autorizado, rastreio de lote quando aplicável.\n\nMundo C — Informal sem rastreio: ausência de COA confiável e ausência de supervisão clínica estruturada — alto risco legal e sanitário.",
      "PASSO A PASSO — ler rótulo ou resumo de portaria.\n\n1. Classifique: alimento, cosmético, suplemento vedado localmente ou medicamento.\n\n2. Leia THC e CBD com unidade (mg por dose, % massa/massa).\n\n3. Busque selo GMP ou farmácia autorizada quando couber.\n\n4. Cruze com prescritor — rótulo não substitui monitoramento clínico.",
      "PERGUNTAS PARA COPIAR NA CONSULTA (médico ou farmacêutico).\n\n• Como esta forma farmacêutica interage com meus medicamentos atuais?\n\n• Qual esquema temporal devo registrar (horários, refeições)?\n\n• Quais sinais devem me levar a ligar antes da próxima consulta?\n\n• Onde encontro informação oficial atualizada sobre importação ou dispensação?",
      "EXEMPLOS. Óleo importado regulado versus frasco informal; flor medicinal com rastreio versus flor sem origem; cosmético com CBD sem dose terapêutica declarada.",
      "ERROS COMUNS. Achar que \"CBD de shopping\" resolve quadro psiquiátrico grave sem avaliação; confundir permissão individual com política geral; presumir UE = Brasil.",
      "SÍNTESE. Você distingue mundos por critérios objetivos (rótulo, prescrição, rastreio) e sabe quando escalar para advogado ou farmacêutico.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Classificar produtos por categoria regulatória genérica usando rótulo e documentação.",
      "Explicar por que decisões jurídicas individuais não substituem consulta personalizada.",
      "Preparar perguntas objetivas ao prescritor sobre titulação e interações usando o bloco copiável desta aula."
    ],
    closingSummary:
      "Fluxograma em três caixas: Baixo THC industrial; Medicinal regulado; Informal sem rastreio — uma pergunta por caixa que só profissional habilitado fecha.",
    quiz: [
      q(
        "Cannabis medicinal, neste curso, significa sobretudo:",
        0,
        "Uso enquadrado legalmente com produtos/prescrito e acompanhamento profissional quando aplicável",
        "Qualquer óleo comprado online sem receita",
        "Maconha social renomeada para parecer ciência",
        "Automedicação sem monitoramento porque é natural"
      ),
      q(
        "Ao ler rótulo, qual é o primeiro passo útil?",
        3,
        "Escolher a embalagem mais bonita",
        "Ignorar unidades de medida",
        "Assumir dose pelo peso corporal sozinho",
        "Identificar categoria do produto (medicamento, cosmético etc.) e teores declarados"
      ),
      q(
        "Sobre Brasil versus outros países:",
        1,
        "Leis são idênticas em todos os continentes",
        "Requer conferência em fonte oficial atualizada; cenário muda e há camadas estaduais/federais nos EUA",
        "Redes sociais substituem Diário Oficial",
        "Se é legal em Amsterdam, é legal no seu endereço automaticamente"
      )
    ],
    professorNotes:
      "Datas nos slides. Evite nomes reais de pacientes. Reforce confidencialidade e estigma.",
    media: MEDIA_STANDARD,
    pedagogy: {
      practicalObjectiveLead: "Separar três mundos: baixo THC industrial, medicinal regulado e informal sem rastreio.",
      practicalExplanation:
        "No Brasil, canabinoides prescritos seguem canais específicos — importação autorizada, registrados quando existirem. Decisões judiciais individuais acrescentam camada que muda; quando citar, diga quando leu.\n\nNos EUA, permissão estadual não apaga tensão federal em vários cantos da vida real.",
      stepByStep: [
        "Ler rótulo ou resumo de portaria: primeiro classifique — alimento, cosmético, suplemento vedado localmente ou medicamento.",
        "Leia THC e CBD com unidade honesta (mg por dose, % massa/massa).",
        "Busque selo GMP ou canal autorizado quando couber.",
        "Cruze com prescritor — rótulo não substitui monitoramento clínico.",
        "Leve pra consulta: interações com remédios atuais; horários pra registrar; sinais de alarme; onde achar informação oficial sobre importação ou dispensação."
      ],
      realExample:
        "Óleo importado regulado versus frasco informal sem origem. Flor medicinal com rastreio versus flor «de amigo». Cosmético com CBD sem dose terapêutica declarada — são categorias diferentes, não só «tem CBD».",
      commonMistakes:
        "Achar que «CBD de shopping» resolve quadro psiquiátrico grave sem avaliação. Confundir decisão judicial individual com política geral do país. Assumir que UE igual Brasil.",
      professionalObservation:
        "Eu atualizo data nos slides todo semestre e corto nome de paciente sem piedade — exemplo vale; exposição não.",
      operationalSummary:
        "Três mundos em uma linha cada:\n\nMundo A — baixo THC industrial/alimento/fibra: olho no limite legal de THC declarado.\n\nMundo B — medicinal regulado: prescrição, rótulo com teores, canal autorizado, rastreio de lote quando existir.\n\nMundo C — informal sem rastreio: sem COA confiável e sem supervisão clínica estruturada — risco legal e sanitário alto.",
      exercise:
        "Desenhe três caixas — Baixo THC industrial; Medicinal regulado; Informal sem rastreio — e escreva uma pergunta em cada que só profissional habilitado fecha de verdade.",
      nextLessonBridge:
        "A seguir: canabinoides no papel — THCA, THC total, LOD/LOQ — pra você ler COA sem pirar."
    }
  },

  "c101-l04-canabinoides": {
    introduction:
      "THC, CBD, CBG, CBN — não são encantamento de marketer; são moléculas com endereço no COA.\n\nEsta aula é laboratório em texto: porcentagem, mg/g, LOD/LOQ, oxidação.\n\nConecta direto com a aula da planta: colheita e armazenagem mudam o que o laudo mostra.",
    body: [
      "OBJETIVO. Interpretar laudos quantitativos básicos e relacionar armazenamento com perfil de canabinoides, sem promessa clínica.",
      "EXPLICAÇÃO. COA lista THCA, CBDA, THC total e CBD total estimados por soma após decarboxilação teórica — cada laboratório declara equação; compare sempre método e unidade. LOD/LOQ informam confiança em valores baixos. THCA alto exposto a luz e oxigênio pode migrar para THC neutro e oxidar a CBN — literatura descreve envelhecimento químico mensurável.",
      "PERGUNTAS ÚTEIS AO LABORATÓRIO OU FORNECEDOR (quando legalmente aplicável).\n\n• Qual acreditação e qual versão de método para potência?\n\n• Unidade é massa seca da flor ou produto acabado?\n\n• Há painel de segurança (pesticidas, metais, micotoxinas) neste lote?\n\n• Como reproduzir o mesmo ensaio em lote futuro?",
      "EXERCÍCIO FICTÍCIO — DUAS LINHAS DE COA (números ilustrativos, não prescrevem uso).\n\nLote 1: THCA 22 %; THC total declarado 19 %; data há 40 dias; armazenagem mal vedada.\n\nLote 2: THCA 22 %; THC total declarado 18,5 %; CBN subiu vs relatório anterior do mesmo cultivar; data há 120 dias.\n\nPergunta de raciocínio: o que mudar primeiro na hipótese — genética ou tempo/oxigênio? Por quê?",
      "PASSO A PASSO — ler COA de produto legal.\n\n1. Laboratório, acreditação, data.\n\n2. Unidade (% massa seca vs mg por unidade).\n\n3. THC total vs THCA isolado — entender precursor.\n\n4. Contaminantes antes de celebrar potência.\n\n5. Guardar PDF com número de lote se acompanha titulação clínica autorizada.",
      "EXEMPLOS. Flor potente com micotoxina acima do permitido reprova; óleo 25 mg/dose pode variar ± faixa do método; CBN alto sugere estoque velho ou armazenagem ruim.",
      "ERROS COMUNS. Comparar países sem converter unidades; ignorar umidade da amostra; \"full spectrum\" sem dados numéricos.",
      "TERMOS. Decarboxilação — perda do grupo carboxila gerando formas neutras. Titulação — ajuste gradual supervisionado clinicamente. Farmacocinética — tempo × concentração plasmática conforme via.",
      "SÍNTESE. COA é documento técnico; envelhecimento impróprio altera química observável — prepara comparação com vias de consumo mais adiante.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Explicar diferença entre THCA/CBDA e THC/CBD neutros em nível introdutório.",
      "Navegar seções típicas de COA: potência, segurança, método.",
      "Relacionar oxidação e tempo com aumento relativo de CBN descrito na literatura."
    ],
    closingSummary:
      "Faça download de COA público anônimo e circule: THC total; data; LOD de contaminantes. O que não entender vira pergunta ao farmacêutico ou prescritor.",
    quiz: [
      q(
        "Por que CBN frequentemente sobe em amostras antigas mal guardadas?",
        2,
        "Porque laboratórios sempre adulteram resultados",
        "Porque CBD vira automaticamente vitamina",
        "Porque THC pode oxidar-se formando mais CBN ao longo do tempo sob luz/oxigênio",
        "Porque terpenos viram THC mágico"
      ),
      q(
        "Ao ler COA, qual prioridade esta aula defende?",
        1,
        "Potência máxima antes de qualquer outra linha",
        "Integridade do laboratório, data, unidades e painel de segurança quando disponível",
        "Ignorar método analítico",
        "Assumir todos os laudos iguais sem acreditação"
      ),
      q(
        "THCA no laudo representa, em linguagem simples:",
        0,
        "Forma ácida precursora que pode converter-se em THC neutro com calor ou tempo",
        "Álcool etílico adicionado ilegalmente",
        "Terpeno aromático",
        "Tipo de fertilizante"
      )
    ],
    professorNotes:
      "Slide com COA anonimizado real. Conversão de unidades simbólica — sem ensinar fraude em ensaio.",
    media: MEDIA_STANDARD,
    pedagogy: {
      practicalObjectiveLead: "Ler COA sem glossário na mão e saber o que pergunta ao laboratório.",
      practicalExplanation:
        "COA lista THCA, CBDA, THC total e CBD total estimados por soma após decarboxilação teórica — cada laboratório declara equação; compare método e unidade.\n\nLOD e LOQ dizem até onde você pode confiar em número baixo.\n\nTHCA alto exposto a luz e oxigênio pode migrar pra THC neutro e oxidar a CBN — envelhecimento químico mensurável na literatura.",
      stepByStep: [
        "Laboratório, credencial, data do laudo.",
        "Unidade clara: % massa seca versus mg por unidade de produto.",
        "THC total versus THCA isolado — entender precursor antes de celebrar potência.",
        "Painel de segurança antes de só festejar potência: contaminantes importam.",
        "Guardar PDF com número de lote se você acompanha titulação clínica autorizada.",
        "Pergunte quando couber: qual método de potência; unidade é flor seca ou produto acabado; há painel de pesticidas, metais, micotoxinas neste lote?"
      ],
      realExample:
        "Exercício fictício com dois lotes: mesmo THCA inicial; um mal vedado há 40 dias, outro envelhecido com CBN subindo versus relatório anterior. O primeiro suspeito a ajustar não é a genética — é tempo, luz e oxigênio.",
      commonMistakes:
        "Comparar países sem converter unidade. Ignorar umidade da amostra. «Full spectrum» bonito no rótulo sem dado numérico.",
      professionalObservation:
        "Eu projeto slide com COA anonimizado de verdade: aluno sente cheiro de papel técnico, não de promessa.",
      operationalSummary:
        "COA é documento técnico, não outdoor.\n\nArmazenagem ruim altera química observável — você já sabe olhar potência e segurança no mesmo arquivo.",
      exercise:
        "Baixe um COA público anônimo e circule com caneta: THC total; data; LOD de contaminantes. O que não entender vira pergunta pro farmacêutico ou prescritor.",
      nextLessonBridge:
        "Terpenos na próxima — aroma, conservação e fim do papo de «esse terpeno cura» sem evidência."
    }
  },

  "c101-l05-terpenos": {
    introduction:
      "Terpeno é volátil — manda no aroma e num pedaço importante da percepção.\n\nOlha como processista: temperatura, oxigênio, luz e tempo são controle de conservação; não são modinha de Instagram.\n\nEsta aula corta o vício de virar nome de terpeno em promessa clínica.",
    body: [
      "OBJETIVO. Correlacionar compostos voláteis com percepção, protocolos caseiros de conservação (onde legal possuir flor seca) e sanidade frente a claims milagrosos.",
      "CIÊNCIA SEM HYPE. Mirceno tende a notas herbáceas; limoneno cítrico; pineno resinoso; linalool floral. Cromatografia mede µg/g — o nariz não é GC-MS. Declarações terapêuticas por terpeno isolado costumam extrapolar evidência; aqui usamos terpenos para entender fragilidade química e qualidade sensorial, não para prescrever tratamento.",
      "EXEMPLO LOTE A VS LOTE B (fictício). Mesmo nome comercial; Lote A secagem lenta em escuro com vedante real mantém topo cítrico; Lote B secagem quente e pote transparente no parapeito perde voláteis leves — mesmo THC total no papel pode parecer \"flat\" ao usuário. Nariz não substitui COA, mas discordância nariz×rótulo merece investigação de processo.",
      "EXPLICAÇÃO. Secagem lenta em escuro com ar suave preserva monoterpenos sensíveis que evaporam acima de ~30–35 °C prolongados (faixa ilustrativa — matriz e equipamento importam).",
      "PASSO A PASSO — conservação doméstica responsável (produto legal).\n\n1. Recipiente opaco com vedante sério.\n\n2. Reguladores de humidade conforme orientação clínica ou protocolo local — decisão médica, não escolar.\n\n3. Evite geladeira se não controlar condensação — risco de mofo.\n\n4. Abrir o pote o mínimo; oxigênio fragmenta terpenos.",
      "EXEMPLOS. Vidro âmbar melhor que pote claro na janela; concentrado aquecido no bolso perde topo aromático; café ao lado contamina odor.",
      "ERROS COMUNS. Congelar sem embalar; misturar genéticas sem etiqueta; confundir cheiro forte com potência alta.",
      "TERMOS. Evaporação — perda física de voláteis. Oxidação — alteração química. Cura — redistribuição de umidade após secagem inicial.",
      "SÍNTESE. Terpenos são ingredientes frágeis: técnica de armazenamento define o que resta ao nariz.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Nomear três terpenos frequentes e associá-los a notas aromáticas.",
      "Descrever como calor, luz e oxigênio degradam voláteis.",
      "Rejeitar narrativa de cura baseada só no nome de um terpeno sem evidência clínica específica."
    ],
    closingSummary:
      "Liste quatro controles (luz, temperatura, oxigênio, umidade) e diga qual sacrificaria primeiro se morasse em lugar muito úmido — e por quê.",
    quiz: [
      q(
        "Secagem muito quente e rápida tende a:",
        1,
        "Aumentar monoterpenos sensíveis",
        "Perder voláteis leves e empobrecer aroma percebido",
        "Ser irrelevante para química",
        "Eliminar necessidade de armazenamento"
      ),
      q(
        "Afirmar que \"limoneno cura ansiedade\" só pelo nome é:",
        3,
        "Evidência nível I",
        "Conduta recomendada em sala",
        "Equivalente a RCT duplo-cego",
        "Redução perigosa de ciência complexa a slogan"
      ),
      q(
        "Recipiente opaco com vedante visa principalmente:",
        0,
        "Reduzir luz e oxigênio que degradam compostos voláteis",
        "Impedir leitura do rótulo",
        "Substituir orientação médica",
        "Aumentar THC por telepatia"
      )
    ],
    professorNotes:
      "Estações com especiarias para treinar nariz sem cannabis, se política permitir.",
    media: MEDIA_INTRO,
    pedagogy: {
      practicalObjectiveLead: "Nomear voláteis com pé no chão e defender conservação sem hype terapêutico.",
      practicalExplanation:
        "Mirceno tende a nota herbácea; limoneno cítrico; pineno resinoso; linalool floral.\n\nCromatografia mede µg/g — o nariz não é cromatógrafo.\n\nTerpeno aqui explica fragilidade química e qualidade sensorial; não substitui evidência clínica nem prescrição.",
      stepByStep: [
        "Recipiente opaco com vedante sério — corta luz e oxigênio que fragmentam monoterpenos.",
        "Reguladores de umidade seguem orientação clínica ou protocolo local — decisão médica.",
        "Evite geladeira se não controlar condensação — mofo entra fácil.",
        "Abra o pote o mínimo possível — cada abertura é oxidação e perda de topo aromático.",
        "Secagem lenta em escuro com ar suave preserva voláteis sensíveis que evaporam com calor prolongado acima de faixa ilustrativa ~30–35 °C — matriz e equipamento mudam o número."
      ],
      realExample:
        "Mesmo nome comercial, dois lotes: A secou devagar no escuro com vedante real — mantém topo cítrico. B secou quente, ficou em pote transparente no parapeito — perde volátil leve. THC total pode parecer parecido no papel e mesmo assim o B cheira «flat». Nariz não substitui COA; discordância nariz × rótulo pede investigação de processo.",
      commonMistakes:
        "Congelar sem embalar direito. Misturar genéticas sem etiqueta. Confundir cheiro forte com potência alta.",
      professionalObservation:
        "Quando política não deixa cheiro de flor na sala, eu monto estação de especiarias — treina nariz sem drama institucional.",
      operationalSummary:
        "Terpenos são ingredientes frágeis: técnica de armazenamento define o que sobra pro nariz.\n\nCalor, luz e oxigênio são seus três inimigos declarados.",
      exercise:
        "Liste quatro controles — luz, temperatura, oxigênio, umidade — e diga qual você sacrificaria primeiro se morasse em lugar muito úmido, e por quê.",
      nextLessonBridge:
        "Depois do nariz, o significado medicinal e recreativo — SEC, THC, CBD e como a planta conversa com o corpo."
    }
  },

  "c101-l06-sistema-endocanabinoide": {
    introduction: [
      "# Significado Medicinal e Recreativo da Cannabis",
      "",
      "## Entenda como a mesma planta pode auxiliar no tratamento de doenças, promover bem-estar e interagir profundamente com o corpo humano",
      "",
      "📖 15 min de leitura",
      "🎯 Nível: Iniciante",
      "",
      "## Muito além do “barato”",
      "",
      "Durante décadas, a cannabis foi reduzida apenas à imagem de uma droga recreativa.",
      "",
      "Mas a ciência moderna revelou algo muito mais profundo:",
      "a cannabis interage diretamente com um sistema biológico natural presente no corpo humano.",
      "",
      "Esse sistema influencia:",
      "",
      "- humor;",
      "- sono;",
      "- fome;",
      "- memória;",
      "- dor;",
      "- imunidade;",
      "- inflamação;",
      "- relaxamento;",
      "- e equilíbrio do organismo.",
      "",
      "Ou seja:",
      "o corpo humano possui mecanismos feitos justamente para interagir com substâncias semelhantes às da cannabis.",
      "",
      "## Nesta aula, você vai compreender:",
      "",
      "- o que é o Sistema Endocanabinoide;",
      "- por que o THC altera a percepção;",
      "- por que o CBD não causa efeito psicoativo;",
      "- como a cannabis pode ser usada medicinalmente;",
      "- e por que diferentes compostos da planta possuem funções distintas."
    ].join("\n"),
    body: [
      "## O Sistema Endocanabinoide (SEC)",
      "",
      "Em 1992, cientistas descobriram um dos sistemas biológicos mais importantes do corpo humano:",
      "o Sistema Endocanabinoide, também chamado de SEC.",
      "",
      "Essa descoberta revolucionou a medicina moderna.",
      "",
      "O SEC funciona como um grande sistema de comunicação e equilíbrio interno do organismo.",
      "",
      "Seu principal objetivo é manter o corpo em estabilidade — algo conhecido como homeostase.",
      "",
      "Imagine o corpo humano como uma máquina extremamente complexa.",
      "",
      "Quando algo sai do equilíbrio:",
      "",
      "- dor;",
      "- estresse;",
      "- ansiedade;",
      "- inflamação;",
      "- falta de sono;",
      "- ou alterações emocionais;",
      "",
      "o Sistema Endocanabinoide atua tentando restaurar o equilíbrio natural.",
      "",
      "## O corpo humano já produz “canabinoides”",
      "",
      "Uma das descobertas mais fascinantes da ciência é que o próprio corpo humano produz substâncias semelhantes às encontradas na cannabis.",
      "",
      "Essas substâncias são chamadas:",
      "",
      "**Endocanabinoides**",
      "",
      "“Endo” significa “interno”.",
      "",
      "Os dois principais são:",
      "",
      "**Anandamida**",
      "**2-AG**",
      "",
      "A anandamida ficou conhecida como:",
      "",
      "**“Molécula da felicidade”**",
      "",
      "O nome vem do sânscrito “Ananda”, que significa:",
      "",
      "- felicidade;",
      "- paz;",
      "- bem-estar interior.",
      "",
      "Ela participa da regulação de:",
      "",
      "- prazer;",
      "- humor;",
      "- motivação;",
      "- memória;",
      "- e relaxamento.",
      "",
      "## Os receptores CB1 e CB2",
      "",
      "O Sistema Endocanabinoide possui receptores espalhados pelo corpo inteiro.",
      "",
      "Os principais são:",
      "",
      "**CB1**",
      "",
      "Encontrados principalmente:",
      "",
      "- no cérebro;",
      "- sistema nervoso;",
      "- memória;",
      "- coordenação;",
      "- percepção;",
      "- emoções.",
      "",
      "É aqui que o THC atua com maior intensidade.",
      "",
      "Por isso o THC pode provocar:",
      "",
      "- relaxamento;",
      "- euforia;",
      "- alteração da percepção;",
      "- aumento do apetite;",
      "- mudanças sensoriais;",
      "- e alteração da percepção do tempo.",
      "",
      "É importante entender:",
      "o THC não “cria” sensações artificiais do nada.",
      "",
      "Ele interage com um sistema que já existe naturalmente no corpo humano.",
      "",
      "**CB2**",
      "",
      "Os receptores CB2 estão mais ligados:",
      "",
      "- ao sistema imunológico;",
      "- inflamações;",
      "- órgãos;",
      "- tecidos;",
      "- e processos de defesa do organismo.",
      "",
      "Por isso a cannabis vem sendo estudada em:",
      "",
      "- dores crônicas;",
      "- inflamações;",
      "- doenças autoimunes;",
      "- recuperação física;",
      "- e tratamentos terapêuticos.",
      "",
      "## THC — O canabinoide psicoativo",
      "",
      "O THC (Delta-9-tetrahidrocanabinol) é o composto psicoativo mais conhecido da cannabis.",
      "",
      "Ele é responsável pelos efeitos associados ao “barato”.",
      "",
      "Mas reduzir o THC apenas a isso seria um erro.",
      "",
      "O THC também possui importantes aplicações medicinais.",
      "",
      "Pesquisas mostram benefícios no auxílio de:",
      "",
      "- dor crônica;",
      "- náuseas da quimioterapia;",
      "- falta de apetite;",
      "- espasmos musculares;",
      "- TEPT;",
      "- glaucoma;",
      "- e insônia.",
      "",
      "A grande questão do THC está na:",
      "",
      "**dosagem e responsabilidade**",
      "",
      "Doses pequenas podem produzir:",
      "",
      "- relaxamento;",
      "- redução da ansiedade;",
      "- melhora do humor;",
      "- e bem-estar.",
      "",
      "Já doses excessivas podem gerar desconforto, especialmente em iniciantes.",
      "",
      "Por isso:",
      "",
      "**menos pode ser mais.**",
      "",
      "## CBD — O canabinoide terapêutico",
      "",
      "O CBD (canabidiol) se tornou um dos compostos mais estudados da medicina moderna.",
      "",
      "Diferente do THC:",
      "",
      "**o CBD não causa efeito psicoativo.**",
      "",
      "Ou seja:",
      "não produz sensação de intoxicação ou alteração intensa da consciência.",
      "",
      "O CBD atua de maneira mais reguladora e anti-inflamatória.",
      "",
      "Pesquisas investigam seu potencial em:",
      "",
      "- epilepsia;",
      "- ansiedade;",
      "- autismo;",
      "- dor neuropática;",
      "- inflamações;",
      "- Parkinson;",
      "- insônia;",
      "- e diversas outras condições.",
      "",
      "Hoje, medicamentos à base de CBD já são aprovados em vários países.",
      "",
      "## Outros canabinoides importantes",
      "",
      "A cannabis possui mais de:",
      "",
      "**140 canabinoides conhecidos**",
      "",
      "Cada um possui funções específicas.",
      "",
      "**CBN**",
      "",
      "Relaciona-se ao relaxamento e sedação.",
      "",
      "Muito estudado para:",
      "",
      "- sono;",
      "- insônia;",
      "- e relaxamento noturno.",
      "",
      "**CBG**",
      "",
      "Conhecido como:",
      "",
      "**“canabinoide mãe”**",
      "",
      "Possui potencial:",
      "",
      "- anti-inflamatório;",
      "- neuroprotetor;",
      "- e antibacteriano.",
      "",
      "**CBC**",
      "",
      "Associado a:",
      "",
      "- humor;",
      "- neurogênese;",
      "- e possíveis efeitos antidepressivos.",
      "",
      "**THCV**",
      "",
      "Estudado por possíveis efeitos:",
      "",
      "- energéticos;",
      "- estimulantes;",
      "- e relacionados ao metabolismo.",
      "",
      "## O efeito entourage (efeito comitiva)",
      "",
      "Uma das teorias mais importantes da cannabis moderna é o:",
      "",
      "**efeito entourage**",
      "",
      "Isso significa que:",
      "",
      "- canabinoides;",
      "- terpenos;",
      "- flavonoides;",
      "- e outros compostos da planta;",
      "",
      "trabalham melhor juntos do que isolados.",
      "",
      "Ou seja:",
      "a planta inteira possui uma inteligência química natural.",
      "",
      "Por isso muitos pacientes relatam melhores resultados com produtos:",
      "",
      "- full spectrum;",
      "- broad spectrum;",
      "- ou extrações completas.",
      "",
      "A cannabis funciona como uma verdadeira sinfonia química.",
      "",
      "## Medicinal × recreativo",
      "",
      "A mesma planta pode ser usada com objetivos completamente diferentes.",
      "",
      "**Uso medicinal**",
      "",
      "Busca:",
      "",
      "- equilíbrio;",
      "- tratamento;",
      "- redução de sintomas;",
      "- qualidade de vida;",
      "- e bem-estar terapêutico.",
      "",
      "Normalmente envolve:",
      "",
      "- dosagens controladas;",
      "- acompanhamento;",
      "- e objetivos específicos.",
      "",
      "**Uso recreativo**",
      "",
      "Está ligado:",
      "",
      "- ao relaxamento;",
      "- socialização;",
      "- criatividade;",
      "- introspecção;",
      "- prazer;",
      "- ou lazer.",
      "",
      "O mais importante é compreender:",
      "",
      "**uso consciente importa.**",
      "",
      "A educação sobre cannabis é fundamental para:",
      "",
      "- redução de danos;",
      "- autocuidado;",
      "- responsabilidade;",
      "- e segurança.",
      "",
      "## Cannabis e medicina moderna",
      "",
      "Hoje, mais de 40 países possuem programas relacionados à cannabis medicinal.",
      "",
      "A ciência moderna voltou a estudar a planta com profundidade.",
      "",
      "O que antes era tratado apenas como tabu, hoje é tema de:",
      "",
      "- universidades;",
      "- pesquisas clínicas;",
      "- hospitais;",
      "- e centros científicos.",
      "",
      "A descoberta do Sistema Endocanabinoide mostrou que a relação entre cannabis e corpo humano é muito mais profunda do que se imaginava.",
      "",
      "## Você sabia?",
      "",
      "O famoso “runner’s high” — sensação de bem-estar após exercícios físicos — possui relação direta com aumento de endocanabinoides naturais no organismo.",
      "",
      "Ou seja:",
      "o próprio corpo produz substâncias semelhantes às da cannabis durante atividades físicas.",
      "",
      "### Depois desta aula, você compreende:",
      "",
      "- ✅ O que é o Sistema Endocanabinoide",
      "- ✅ Como o THC e o CBD atuam no organismo",
      "- ✅ Diferenças entre CB1 e CB2",
      "- ✅ O que são endocanabinoides",
      "- ✅ Como a cannabis pode atuar medicinalmente",
      "- ✅ O que é o efeito entourage",
      "- ✅ Diferenças entre uso medicinal e recreativo",
      "- ✅ A importância do uso consciente e da redução de danos",
      "",
      "## Conclusão",
      "",
      "Compreender a cannabis é compreender também o funcionamento do corpo humano.",
      "",
      "A descoberta do Sistema Endocanabinoide abriu uma nova fronteira para a medicina moderna e ajudou a derrubar antigos preconceitos sobre a planta.",
      "",
      "A cannabis não é apenas uma substância.",
      "Ela é:",
      "",
      "- história;",
      "- ciência;",
      "- medicina;",
      "- cultura;",
      "- e conhecimento ancestral.",
      "",
      "E quanto mais aprendemos sobre ela, mais percebemos que ainda existe muito a descobrir.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Explicar o Sistema Endocanabinoide (SEC) como rede de homeostase e comunicação interna.",
      "Distinguir endocanabinoides (anandamida, 2-AG), receptores CB1 e CB2 e o que isso implica para THC e CBD.",
      "Caracterizar THC (psicoatividade, dose-responsa) e CBD (sem intoxicação típica) em linguagem introdutória.",
      "Nomear papéis introdutórios de CBN, CBG, CBC e THCV sem prometer efeitos individuais.",
      "Descrever o efeito entourage e por que espectros completos são discutidos na literatura.",
      "Contrastar uso medicinal (objetivos, acompanhamento) e recreativo, reforçando educação e redução de danos."
    ],
    closingSummary:
      "Você fecha com o mapa interior: SEC, receptores, moléculas da planta e do corpo, entourage e dois propósitos de uso — sempre com consciência de que ciência explica mecanismos, não substitui decisão clínica nem legalidade local.",
    quiz: [
      q(
        "Segundo esta aula, o CBD é melhor descrito como:",
        1,
        "Sinônimo químico do THC com o mesmo efeito psicoativo",
        "Composto que não produz intoxicação psicoativa típica associada ao THC",
        "Substância que só liga em receptores fora do sistema nervoso",
        "Molécula que elimina a necessidade de acompanhamento médico"
      ),
      q(
        "Os receptores CB1 são enfatizados principalmente porque:",
        0,
        "Concentrados sobretudo no sistema nervoso central — interface central dos efeitos do THC na percepção e humor",
        "Existem apenas na pele das mãos",
        "Não interagem com canabinoides exógenos",
        "Substituem totalmente a produção de insulina"
      ),
      q(
        "A ideia do “efeito entourage” refere-se a:",
        2,
        "Uso exclusivo de THC isolado em laboratório",
        "Eliminação de terpenos para aumentar segurança",
        "Múltiplos compostos da planta (canabinoides, terpenos, flavonoides etc.) potencialmente atuando de forma complementar em relação ao isolado",
        "Efeito médico garantido em qualquer produto comercializado informalmente"
      )
    ],
    professorNotes:
      "Separar evidência populacional de promessa individual; lembrar que “mais de 40 países” são políticas em mudança — cite data da fonte. Útil contrastar entourage (hipótese/teoria discutida) com marketing de rótulo.",
    media: { ...MEDIA_STANDARD, needsInfographic: true }
  },

  "c101-l07-usos-e-reducao-de-danos": {
    introduction:
      "Redução de danos é engenharia de risco quando já existe exposição a psicoativo — não é «liberar geral» nem aesthetic de festival.\n\nAqui você monta cenário com checklist; eu não prescrevo dose nem mistura pra terceiro.\n\nCompartilhar número de emergência e material neutro é uma coisa; virar consultório ambulante de dose é outra.",
    body: [
      "OBJETIVO. Construir protocolos situacionais (evento, estrada, lar com crianças) que reduzam trauma, sobrecarga subjetiva intensa e consequências jurídicas, sem romantizar uso.",
      "ÉTICA AO \"AJUDAR\" ALGUÉM. Pode indicar números de emergência, incentivar conversa com profissional e compartilhar materiais educativos neutros. Não copie doses, não recomende misturas sedativas, não incentive condução ou trabalho perigoso sob influência — mesmo que \"todo mundo faça\".",
      "EXPLICAÇÃO. Baixa dose inicial com supervisão clínica quando aplicável reduz episódios \"too much\". Mistura com álcool ou benzodiazepínicos aumenta sedação e queda. Dirigir sob THC onde proibido ou com tolerância zero é risco jurídico e de vida.",
      "CENÁRIO EVENTO (uso onde legal para adultos).\n\n1. Limite prévio por escrito.\n\n2. Água e alimento leve disponíveis.\n\n3. Pessoa sóbria de confiança.\n\n4. Endereço de emergência salvo.\n\n5. Produto em embalagem original rotulada.",
      "CENÁRIO LAR COM CRIANÇAS.\n\n1. Armário trancado alto.\n\n2. Embalagem à prova de criança.\n\n3. Linguagem honesta — nunca \"doce\".\n\n4. Descarte conforme farmácia/local.",
      "SINAIS DE ALARME (acionar ajuda formal).\n\n1. Confusão súbita ou desorientação nova.\n\n2. Dor torácica ou falta de ar.\n\n3. Pensamentos de autolesão ou violência.\n\n4. Vómito incoercível ou desidratação grave.",
      "EXEMPLOS. Comestível sem rótulo levando a PS; CNH perdida por teste saliva; interações com psicofármacos subnotificadas.",
      "SÍNTESE. Dois fluxogramas — adulto fora de casa e guardião em casa — centrados em transparência e ajuda formal.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Redigir checklist de redução de danos para dois cenários distintos.",
      "Explicar por que misturas com depressores do SNC são especialmente perigosas.",
      "Distinguir compartilhamento educativo seguro de orientação clandestina sobre dose ou mistura."
    ],
    closingSummary:
      "Troque com colega um item que cada checklist esqueceu — objetivo é cobrir risco social real.",
    quiz: [
      q(
        "Misturar THC com álcool ou benzodiazepínicos tende a:",
        1,
        "Reduzir sempre o efeito",
        "Potencializar sedação e risco de trauma por queda ou parada respiratória em extremos",
        "Ser neutro farmacologicamente",
        "Substituir hidratação"
      ),
      q(
        "Guarda doméstica responsável inclui:",
        2,
        "Deixar flora na mesa para \"naturalizar\" criança",
        "Rotular como docinho para não assustar",
        "Armazenamento trancado, embalagem à prova de criança e linguagem honesta sobre risco",
        "Esconder produtos sem sistema — suficiente se adulto está em casa"
      ),
      q(
        "Redução de danos no trânsito implica:",
        0,
        "Não dirigir sob influência psicoativa onde proibido ou inseguro",
        "Dirigir devagar compensa",
        "Cannabis não altera tempo de reação",
        "Polícia não testa THC em lugar nenhum"
      )
    ],
    professorNotes:
      "Cartão com emergência regional e CVV. Zero glamourização de uso excessivo.",
    media: MEDIA_STANDARD,
    pedagogy: {
      practicalObjectiveLead: "Protocolos por cenário — evento, estrada, lar com criança — sem romantizar uso.",
      practicalExplanation:
        "Dose baixa no começo com supervisão clínica quando existe reduz episódio «demais». Mistura com álcool ou benzodiazepínico empurra sedação e queda.\n\nDirigir sob THC onde é proibido ou com tolerância zero é risco jurídico e de vida — sem paleativa.",
      stepByStep: [
        "Cenário evento (onde legal pra adulto): limite por escrito antes; água e comida leve; pessoa sóbria de confiança; endereço de emergência salvo; produto na embalagem original rotulada.",
        "Cenário lar com criança: armário alto trancado; embalagem à prova de criança; linguagem honesta sobre risco — nunca «doce»; descarte conforme farmácia ou regra local.",
        "Sinais pra acionar ajuda formal de verdade: confusão nova; dor torácica ou falta de ar; pensamento de autolesão ou violência; vômito que não para ou desidratação forte.",
        "Ética ao «ajudar»: pode passar telefone de emergência, empurrar conversa com profissional, dividir material educativo neutro. Não copia dose de strangers, não recomenda coquetel sedativo, não incentiva direção ou máquina perigosa sob influência."
      ],
      realExample:
        "Comestível sem rótulo indo parar em PS; carteira de motorista perdida por teste de saliva; interação com psicofármaco que a pessoa «esqueceu» de contar pro médico.",
      commonMistakes:
        "Achar que todo mundo mistura então é seguro. Ensinar dose pelo WhatsApp como se fosse recipe. Glamour em uso pesado.",
      professionalObservation:
        "Eu levo cartão físico com CVV e emergência regional — papel na mão gruda mais que slide bonito.",
      operationalSummary:
        "Dois mundos: adulto fora de casa e guardião em casa — ambos pedem transparência e ajuda formal quando escala.\n\nRedução de danos honra risco real; não empurra narrativa de machão.",
      exercise:
        "Escreve dois checklists rápidos — festa segura e casa com criança — e troca um item com colega pra ver o que cada um esqueceu.",
      nextLessonBridge:
        "Formas de consumo na sequência: mesma molécula, via diferente — curva e armadilha mudam."
    }
  },

  "c101-l08-formas-consumo": {
    introduction:
      "Via de administração redesenha a curva tempo × efeito — e também o drama pulmonar ou intestinal.\n\nInalação térmica, combustão, oral e tópico não são «preferência estética»; são farmacologia básica.\n\nPotência bonita no COA não diz velocidade no organismo — esta aula amarra os dois papéis.",
    body: [
      "OBJETIVO. Comparar vias quanto a início, duração e armadilhas clássicas.",
      "EXPLICAÇÃO. Inalação atinge picos mais rápidos; primeira passagem hepática na ingestão atrasa pico e aumenta variabilidade enzimática. Tópicos frequentemente não geram níveis sistémicos altos — marketing costuma superestimar absorção sistémica.",
      "LINHA DO TEMPO ESBOÇADA — ORAL VS INALAÇÃO ÚNICA (modelo didático, não dose individual).\n\nInalação (ilustrativo): efeito perceptível costuma subir mais cedo no eixo de horas; declínio tende a ser mais rápido que oral.\n\nOral: curva prolongada — erro típico é reforçar dose antes das 1,5–2 h porque \"não bateu\", precipitando sobrecarga quando o primeiro delta ainda está subindo.",
      "PASSO A PASSO — ingestível em contexto adulto onde permitido.\n\n1. Registre horário da primeira dose pequena.\n\n2. Aguarde pelo menos 120 minutos antes de complementar salvo orientação profissional contrária.\n\n3. Não misture com álcool na mesma curva de aprendizado.\n\n4. Ambiente calmo na primeira experiência oral.",
      "PASSO A PASSO — inalação térmica versus combustão.\n\n1. Vaporização reduz mas não elimina irritantes respiratórios.\n\n2. DPOC/asma: evitar inalação sem pneumologista.\n\n3. Limpar equipamento para evitar biofilme.",
      "EXEMPLOS. Turista come brownie inteiro porque \"demorou\"; idoso com enzimas competindo com medicamentos; vídeo de dab caseiro — risco térmico/químico.",
      "ERROS COMUNS. Converter mg oral em mg inalado sem clínica; achar que vape descartável é \"só vapor\"; solventes domésticos para extrair — incêndio.",
      "TERMOS. Biodisponibilidade — fração que chega à circulação. Primeira passagem — metabolização hepática inicial.",
      "SÍNTESE. Escolha via sabendo troca velocidade × previsibilidade; evita reforço precoce oral.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Contrastar curvas de início rápido versus tardio entre vias.",
      "Explicar erro de re-dose precoce em via oral usando a linha do tempo desta aula.",
      "Relacionar combustão com agravo respiratório genérico e COA com biodisponibilidade, não com velocidade automática."
    ],
    closingSummary:
      "Desenhe 0–8 h com duas curvas grosseiras (oral vs inalação) e marque onde usuários costumam errar ao tomar segunda dose.",
    quiz: [
      q(
        "Por que esperar antes de reforçar dose oral?",
        3,
        "Porque metabolismo não existe",
        "Porque oral age sempre em 30 segundos",
        "Porque THC oral não passa fígado",
        "Porque o pico pode tardar horas e uma dose extra precipita desconforto intenso"
      ),
      q(
        "Vaporizar versus fumar, em saúde respiratória de alto nível:",
        1,
        "São idênticos biologicamente",
        "Vapor pode reduzir subprodutos da combustão mas não isenta risco respiratório",
        "Fumar é sempre mais seguro",
        "Ambos curam DPOC"
      ),
      q(
        "Tópicos cosméticos frequentemente:",
        2,
        "Garantem efeito sistêmico forte sempre",
        "Substituem Rx sem estudo",
        "Têm absorção sistêmica limitada dependendo da formulação — checar evidência",
        "São irrelevantes para dermatologia"
      )
    ],
    professorNotes:
      "Proibir tutorial de solvente. Curvas esquemáticas sem doses numéricas irresponsáveis.",
    media: MEDIA_STANDARD,
    pedagogy: {
      practicalObjectiveLead: "Comparar início, duração e armadilha clássica de cada via.",
      practicalExplanation:
        "Inalação sobe rápido no corpo; oral atrasa pico por primeira passagem hepática e variável enzimática explode entre pessoas.\n\nTópico cosmético raramente gera pico sistêmico alto — marketing costuma mentir bonito sobre absorção.",
      stepByStep: [
        "Via oral (onde permitido): anota horário da primeira dose pequena; espera pelo menos 120 minutos antes de complementar salvo orientação médica diferente; sem álcool na mesma curva de aprendizado; ambiente calmo na primeira vez.",
        "Inalação térmica vs combustão: vapor reduz mas não zera irritante respiratório; quem tem DPOC ou asma não inala sem pneumologista; limpa equipamento pra fugir de biofilme.",
        "Erro clássico oral: reforça dose antes de 1h30–2h porque «não bateu» — primeira onda ainda subindo e a segunda vira sobrecarga."
      ],
      realExample:
        "Turista manda brownie inteiro porque «demorou». Idoso com enzimas brigando com remédio. Vídeo de dab improvisado — risco térmico e químico junto.",
      commonMistakes:
        "Converter mg oral em mg inalado na unha. Acreditar que vape descartável é «só vapor». Extrato caseiro com solvente improvisado — incêndio.",
      professionalObservation:
        "Slide só com formato de curva, sem número irresponsável de dose — aluno aprende forma, não copypaste perigoso.",
      operationalSummary:
        "Escolher via é aceitar troca velocidade × previsibilidade.\n\nCOA fala potência química; não substitui entender curva no corpo.",
      exercise:
        "Desenha eixo 0–8 h com duas curvas grosseiras — oral e inalação — e marca onde a galera costuma tomar segunda dose cedo demais.",
      nextLessonBridge:
        "Em seguida: legalidade do cultivo e cenário jurídico — Brasil, decisões, ANVISA e o que muda no mundo."
    }
  },

  "c101-l09-legalidade-br-eua": {
    introduction: [
      "# Legalidade do Cultivo de Cannabis",
      "",
      "## Entenda o cenário jurídico da cannabis no Brasil e no mundo, os direitos do usuário, os riscos legais e os caminhos existentes para acesso medicinal",
      "",
      "📖 18 min de leitura",
      "🎯 Nível: Iniciante",
      "⚖️ Conteúdo educacional importante",
      "",
      "## A cannabis e a lei: um cenário em transformação",
      "",
      "Poucas plantas no mundo geram tantas discussões jurídicas quanto a cannabis.",
      "",
      "Ao mesmo tempo em que diversos países avançam na disciplina normativa:",
      "",
      "- milhões de pessoas ainda são criminalizadas;",
      "- pacientes lutam por acesso medicinal;",
      "- cultivadores buscam segurança jurídica;",
      "- e governos tentam adaptar leis antigas a uma nova realidade científica.",
      "",
      "A cannabis vive hoje um dos maiores processos de transformação cultural, médica e política da história recente.",
      "",
      "## Nesta aula, você vai compreender:",
      "",
      "- o que diz a legislação brasileira;",
      "- como funciona o Habeas Corpus para cultivo;",
      "- o papel da ANVISA;",
      "- o cenário internacional;",
      "- e por que a regulamentação da cannabis está mudando em tantos lugares."
    ].join("\n"),
    body: [
      "## ⚠️ Aviso importante",
      "",
      "Este conteúdo possui finalidade exclusivamente:",
      "",
      "- educacional;",
      "- informativa;",
      "- cultural;",
      "- e de redução de danos.",
      "",
      "A legislação brasileira ainda possui restrições relacionadas ao cultivo da cannabis.",
      "",
      "O THCProce Campus:",
      "",
      "- não incentiva atividades ilegais;",
      "- não substitui orientação jurídica;",
      "- e recomenda consulta com advogado especializado antes de qualquer decisão relacionada ao cultivo medicinal.",
      "",
      "Nosso objetivo é informar o aluno sobre:",
      "",
      "- seus direitos;",
      "- o cenário jurídico atual;",
      "- e os caminhos legais existentes.",
      "",
      "## A Lei de Drogas no Brasil",
      "",
      "A legislação principal relacionada à cannabis no Brasil é:",
      "",
      "**Lei 11.343/2006**",
      "",
      "Conhecida como **Lei de Drogas**.",
      "",
      "Ela diferencia:",
      "",
      "- usuário;",
      "- e traficante.",
      "",
      "Porém, existe um grande problema:",
      "",
      "**a lei não definiu quantidades objetivas.**",
      "",
      "Isso significa que, historicamente, a diferenciação entre:",
      "",
      "- uso pessoal;",
      "- e tráfico;",
      "",
      "acabou ficando muitas vezes sujeita à interpretação policial e judicial.",
      "",
      "## Artigo 28 — usuário",
      "",
      "O Artigo 28 trata do **porte para consumo pessoal**.",
      "",
      "A legislação prevê medidas administrativas como:",
      "",
      "- advertência;",
      "- prestação de serviços;",
      "- medidas educativas.",
      "",
      "**Importante:** o STF decidiu que o porte para uso pessoal não deve receber tratamento criminal da mesma forma que crimes violentos.",
      "",
      "Nos últimos anos, o debate avançou significativamente.",
      "",
      "A discussão jurídica moderna passou a considerar:",
      "",
      "- proporcionalidade;",
      "- liberdade individual;",
      "- redução de danos;",
      "- e direito à saúde.",
      "",
      "## O debate sobre quantidade e cultivo",
      "",
      "Um dos temas mais discutidos atualmente é:",
      "",
      "**autocultivo para uso pessoal**",
      "",
      "Muitos juristas argumentam que:",
      "",
      "- cultivar para consumo próprio;",
      "- sem finalidade comercial;",
      "- e sem vínculo com tráfico;",
      "",
      "não deveria ser tratado da mesma forma que organizações criminosas.",
      "",
      "Esse debate cresce principalmente porque **cultivar reduz contato com o mercado ilegal**.",
      "",
      "Muitos pacientes e usuários defendem que o autocultivo:",
      "",
      "- aumenta segurança;",
      "- melhora qualidade;",
      "- reduz riscos;",
      "- permite controle do produto;",
      "- e evita exposição ao tráfico.",
      "",
      "## Habeas Corpus para cultivo medicinal",
      "",
      "Nos últimos anos, muitas pessoas no Brasil passaram a buscar **autorização judicial** para cultivar cannabis medicinalmente.",
      "",
      "Esse mecanismo ficou conhecido como **Habeas Corpus preventivo** ou **salvo-conduto** (na linguagem cotidiana do debate público — o nome jurídico exato e os efeitos variam conforme caso e tribunal).",
      "",
      "Ele busca proteger pacientes que precisam cultivar cannabis para:",
      "",
      "- produção de óleo;",
      "- tratamento terapêutico;",
      "- controle de sintomas;",
      "- ou acesso medicinal contínuo.",
      "",
      "## Como funciona o processo (visão geral educativa)",
      "",
      "Normalmente o processo envolve:",
      "",
      "- prescrição médica;",
      "- laudos;",
      "- documentação clínica;",
      "- justificativa terapêutica;",
      "- e ação judicial conduzida por advogado.",
      "",
      "Muitos tribunais brasileiros passaram a conceder decisões favoráveis em hipóteses específicas.",
      "",
      "Diversos pacientes utilizam cannabis para (sempre sob orientação profissional quando aplicável):",
      "",
      "- epilepsia;",
      "- dores crônicas;",
      "- autismo;",
      "- Parkinson;",
      "- ansiedade;",
      "- TEPT;",
      "- fibromialgia;",
      "- e outras condições.",
      "",
      "## A importância das associações",
      "",
      "O Brasil também viu o crescimento de **associações de pacientes**.",
      "",
      "Essas associações ajudam pacientes através de:",
      "",
      "- acolhimento;",
      "- suporte jurídico;",
      "- informação;",
      "- acesso a derivados;",
      "- e orientação medicinal.",
      "",
      "Algumas se tornaram referência nacional.",
      "",
      "As associações tiveram papel fundamental na humanização do debate sobre cannabis no Brasil.",
      "",
      "## RDC 660 e a ANVISA",
      "",
      "A **RDC 660** da ANVISA representa um marco importante.",
      "",
      "Ela disciplina **importação de produtos de cannabis** mediante prescrição médica e requisitos sanitários.",
      "",
      "Embora não autorize cultivo recreacional amplo, a RDC reconhece oficialmente:",
      "",
      "- o uso medicinal da cannabis;",
      "- a necessidade terapêutica;",
      "- e o acesso controlado ao tratamento.",
      "",
      "Muitos pacientes brasileiros utilizam produtos importados legalmente por esse canal.",
      "",
      "## O problema do alto custo",
      "",
      "Apesar dos avanços, o acesso ainda é difícil para muitas famílias.",
      "",
      "Produtos importados podem custar **centenas ou milhares de reais por mês**.",
      "",
      "Isso fez crescer:",
      "",
      "- o debate sobre autocultivo;",
      "- associações;",
      "- e regulamentação nacional.",
      "",
      "Muitos pacientes passaram a defender a ideia de **“cultivar para sobreviver”**, especialmente em tratamentos contínuos — expressão do movimento social, não norma automática.",
      "",
      "## O cenário mundial da cannabis",
      "",
      "A regulamentação global mudou rapidamente nos últimos anos.",
      "",
      "Hoje existem países ou jurisdições com modelos que incluem:",
      "",
      "- cannabis medicinal;",
      "- descriminalização;",
      "- clubes canábicos;",
      "- autocultivo;",
      "- e mercados regulamentados.",
      "",
      "### Países com disciplina ampla (exemplos citados no texto-base)",
      "",
      "Alguns países ou regiões permitem combinações de uso medicinal, recreativo, cultivo e comércio regulamentado, **conforme seu ordenamento** — exemplos frequentemente citados na imprensa especializada:",
      "",
      "- Canadá;",
      "- Uruguai;",
      "- Alemanha;",
      "- Malta;",
      "- diversos estados dos EUA.",
      "",
      "Esses modelos são estudados por:",
      "",
      "- impacto no mercado ilegal;",
      "- arrecadação;",
      "- controle de qualidade;",
      "- e dinâmica econômica.",
      "",
      "### Países com foco medicinal primeiro (exemplos)",
      "",
      "Outros países avançaram primeiro no uso medicinal:",
      "",
      "- Brasil;",
      "- Portugal;",
      "- Israel;",
      "- Austrália;",
      "- Colômbia;",
      "- Chile;",
      "- Itália.",
      "",
      "Nesses locais, a cannabis passou a ser tratada, em parte, como questão de saúde pública.",
      "",
      "## Guerra às drogas e impactos sociais",
      "",
      "Durante décadas, a cannabis foi associada a:",
      "",
      "- criminalidade;",
      "- preconceito;",
      "- desinformação;",
      "- e campanhas políticas de medo.",
      "",
      "A chamada **“guerra às drogas”** produziu impactos profundos:",
      "",
      "- encarceramento em massa;",
      "- violência;",
      "- perseguição social;",
      "- e desigualdade.",
      "",
      "Hoje, muitos especialistas defendem políticas mais **humanas**, **baseadas em evidência** e voltadas à **redução de danos**.",
      "",
      "## Redução de danos e uso consciente",
      "",
      "Um dos conceitos mais importantes da educação canábica moderna é **redução de danos**.",
      "",
      "Isso significa:",
      "",
      "- informar;",
      "- orientar;",
      "- educar;",
      "- e reduzir riscos relacionados ao uso.",
      "",
      "O conhecimento protege muito mais do que a desinformação.",
      "",
      "Educação canábica responsável envolve:",
      "",
      "- consciência;",
      "- responsabilidade;",
      "- qualidade;",
      "- respeito à saúde.",
      "",
      "## O futuro da cannabis no Brasil",
      "",
      "O Brasil vive um momento de intensa transformação no debate público.",
      "",
      "Cresce a discussão sobre:",
      "",
      "- medicinal;",
      "- cultivo;",
      "- associações;",
      "- regulamentação;",
      "- e direitos do usuário.",
      "",
      "Ao mesmo tempo:",
      "",
      "- médicos estudam mais;",
      "- universidades pesquisam;",
      "- pacientes relatam benefícios em contextos autorizados;",
      "- e decisões judiciais criam precedentes em casos concretos.",
      "",
      "A tendência global mostra que a cannabis está deixando de ser tratada **apenas** como caso policial e passando a ser discutida como:",
      "",
      "- saúde;",
      "- ciência;",
      "- economia;",
      "- e direitos individuais.",
      "",
      "## Você sabia?",
      "",
      "- O Brasil já teve incentivo ao cultivo de cânhamo no período colonial.",
      "- O mercado legal de cannabis movimenta bilhões de dólares no mundo.",
      "- Israel é um dos países mais citados em pesquisa medicinal com cannabis.",
      "- Milhares de brasileiros já obtiveram decisões judiciais relacionadas a cultivo medicinal em hipóteses específicas.",
      "- O sistema endocanabinoide só foi descoberto em 1992.",
      "",
      "### Depois desta aula, você compreende:",
      "",
      "- ✅ O que diz a Lei de Drogas no Brasil",
      "- ✅ O papel do Artigo 28",
      "- ✅ O que é o debate sobre HC / autorização judicial para cultivo medicinal",
      "- ✅ Como a RDC 660 da ANVISA se insere no acesso a produtos importados",
      "- ✅ O cenário internacional da cannabis",
      "- ✅ O impacto da guerra às drogas",
      "- ✅ A importância da redução de danos",
      "- ✅ Como o debate sobre cannabis está evoluindo no mundo",
      "",
      "## Conclusão",
      "",
      "A história da cannabis e da legislação mostra que o conhecimento costuma ser mais poderoso do que o medo.",
      "",
      "Enquanto o mundo avança cientificamente, muitas pessoas continuam buscando **acesso seguro**, **qualidade de vida**, **autonomia** e **dignidade**.",
      "",
      "Compreender a legalidade da cannabis é compreender também **direitos**, **responsabilidade**, **saúde** e **transformação social**.",
      "",
      "A informação correta — sempre cruzada com **fonte oficial** e **assessoria profissional** quando o caso for pessoal — é uma das ferramentas mais importantes para um futuro mais consciente e equilibrado.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Reconhecer a Lei 11.343/2006 e o Art. 28 como marcos centrais do debate sobre usuário e porte no Brasil.",
      "Descrever, em nível introdutório, o papel da Justiça e do HC/salvo-conduto no debate sobre cultivo medicinal (sempre caso a caso).",
      "Explicar a RDC 660/ANVISA como marco de importação controlada com prescrição, sem confundir com cultivo recreacional amplo.",
      "Contrastar modelos internacionais citados e evitar generalizar: cada país tem ordenamento próprio.",
      "Relacionar guerra às drogas, encarceramento e desigualdade com a atual busca por políticas mais humanas e baseadas em evidência.",
      "Defender redução de danos e uso consciente como eixo educacional — sem substituir advogado ou médico."
    ],
    closingSummary:
      "Você sai desta aula com mapa mental: Lei de Drogas e lacunas de quantidade, vias judiciais e associações, importação ANVISA versus custo, panorama global e por que a sala THCProce continua insistindo em fonte datada e consultório jurídico para decisão pessoal.",
    quiz: [
      q(
        "No Brasil, a aula cita como legislação principal relacionada à cannabis:",
        1,
        "Lei 10.406/2002 apenas",
        "Lei 11.343/2006 (Lei de Drogas)",
        "Somente resoluções municipais genéricas",
        "Exclusivamente normas internacionais sem recepção"
      ),
      q(
        "A RDC 660 da ANVISA é apresentada principalmente como marco de:",
        0,
        "Importação de produtos de cannabis com prescrição e requisitos sanitários",
        "Autorização federal automática de cultivo recreacional em qualquer quantidade",
        "Eliminação da distinção usuário/traficante no código penal",
        "Substituição total de decisão judicial em todos os casos"
      ),
      q(
        "Segundo o aviso desta aula, o THCProce Campus:",
        2,
        "Substitui orientação jurídica individual de advogado em decisões de cultivo",
        "Incentiva cultivo sem verificar enquadramento jurídico",
        "Tem finalidade educativa e recomenda advogado especializado antes de decisões sobre cultivo medicinal",
        "Garante salvo-conduto judicial a qualquer aluno"
      )
    ],
    professorNotes:
      "Atualizar ano de citações normativas; reforçar diferença entre relatório jornalístico e ementa/PDF. Útil convidar biólogo-do-direito ou advogado para 20 min de perguntas — sem gravação de conselho individual a terceiros.",
    media: { ...MEDIA_STANDARD, needsInfographic: true }
  },

  "c101-l10-seguranca-limites": {
    introduction:
      "Fechamos o arco ético com conversa de adulto: o que esse curso entrega com rigor — e o que você não pode fingir que ele promete.\n\nIsso conversa com boas-vindas e com redução de danos; aqui o foco é política editorial, menores, saúde mental e postagem.\n\nMenos ambiguidade no combinado, menos acidente previsível na vida real.",
    body: [
      "O QUE ESTE CURSO OFERECE. Alfabetização técnica: ler COA, entender vias, reconhecer voláteis, preparar perguntas clínicas, pesquisar lei em fonte primária, aplicar redução de danos responsável e encaminhar para salas avançadas do campus com pré-requisitos claros.",
      "O QUE ESTE CURSO NÃO FAZ. Não prescreve, não promete cura, não ensina crime nem evasão de fiscalização, não substitui psiquiatria ou advocacia.",
      "LIMITES E SEGURANÇA. Histórico de psicose ou bipolaridade não tratados exige conversa psiquiátrica antes de experimentação recreativa com THC — não é moralismo, é farmacologia de risco.",
      "PASSO A PASSO — casa segura.\n\n1. Inventário honesto de psicoativos incluindo álcool.\n\n2. Travas físicas e digitais com menores.\n\n3. Conversa franca com rede de apoio sobre objetivos terapêuticos autorizados.",
      "INTERNET RESPONSÁVEL.\n\n1. Não filmar terceiros intoxicados sem consentimento.\n\n2. Sem tutorial de solvente ou explosivo.\n\n3. Rotular opinião versus evidência ao compartilhar.",
      "CONCEITOS (PORTUGUÊS). Dever de cuidado (duty of care) — obrigação mínima de não agravar risco alheio com conselho negligente. Gatilho (trigger) — estímulo que pode reativar quadro psiquiátrico em pessoa vulnerável — comunicar ao profissional.",
      "EXEMPLOS. Crise de ansiedade isolada sem ajuda; adolescente acha produto \"legal\" porque pai escondeu mal; post irresponsável custando emprego.",
      "SÍNTESE. Contrato ético explícito — menos ambiguidade, menos acidente previsível.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Listar três entregas positivas do Cannabis 101 e três limites duros.",
      "Planejar mitigação doméstica para convivência com menores.",
      "Explicar dever de cuidado e gatilho em contexto de comunicação responsável."
    ],
    closingSummary:
      "Uma frase de política pessoal de postagem prudente — exemplo: \"Compartilho apenas comunicados oficiais ou artigos com métodos explícitos citados\".",
    quiz: [
      q(
        "O Cannabis 101 compromete-se a:",
        2,
        "Receita magistral universal",
        "Evasão de fiscalização como módulo bonus",
        "Educação responsável sem prometer cura nem orientar crime",
        "Garantia de emprego na indústria ilegal"
      ),
      q(
        "Histórico de psicose não tratada e THC recreativo:",
        1,
        "Combinação trivia irrelevante",
        "Deve ser discutido urgentemente com psiquiatra antes de qualquer experimentação",
        "É sempre seguro em baixa dose mágica",
        "Substitui antipsicótico"
      ),
      q(
        "Armazenamento com menores exige:",
        3,
        "Gaveta sem tranca porque confiança",
        "Rotular como vitaminas",
        "Mostrar como piada",
        "Barreira física e linguagem honesta sobre risco"
      )
    ],
    professorNotes:
      "Folha CAPS/CVV e política escolar sobre substâncias. Sem culpar vítimas.",
    media: MEDIA_INTRO,
    pedagogy: {
      practicalObjectiveLead: "Assinar de alto a baixo o que o 101 cobre — e o que continua sendo trabalho de médico, advogado ou psiquiatra.",
      practicalExplanation:
        "O curso entrega alfabetização técnica: COA, via de uso, terpeno com pé no chão, pergunta clínica, lei em fonte primária, redução de danos com rigor.\n\nEle não prescreve, não promete cura, não ensina crime nem gambiarra fiscal, não substitui psiquiatria nem escritório de advocacia.",
      stepByStep: [
        "Casa segura: inventário honesto de psicoativo incluindo álcool.",
        "Trava física e digital pra menor — conversa franca com rede de apoio sobre tratamento autorizado.",
        "Internet: sem filmar terceiro alterado sem consentimento; sem tutorial de solvente ou explosivo; separar opinião de evidência quando compartilhar.",
        "Histórico de psicose ou bipolaridade sem tratamento estruturado: conversa psiquiátrica antes de brincar com THC recreativo — é farmacologia de risco, não sermão."
      ],
      realExample:
        "Ansiedade forte parada no quarto sem ajuda; adolescente achando produto «legal» porque estava mal guardado; post irresponsável virando processo ou demissão.",
      commonMistakes:
        "Virar guru de dose em grupo fechado. Tratar dever de cuidado como frescura. Confundir likes com evidência.",
      professionalObservation:
        "Eu deixo folha de CAPS e CVV na mesa — política pública também é técnica de redução de danos.",
      operationalSummary:
        "Dever de cuidado: não piorar risco alheio com conselho mole.\n\nGatilho: estímulo que pode reativar quadro psiquiátrico — comunica pro profissional, não pro story.",
      exercise:
        "Escreve uma frase de política pessoal de postagem — exemplo: «só compartilho comunicado oficial ou artigo com método explícito citado».",
      nextLessonBridge:
        "Última parada: escolher próxima trilha no campus com critério de segurança."
    }
  },

  "c101-l11-proximas-trilhas": {
    introduction:
      "Chegamos no fecho orientador: mapa não é decoração — é decisão de pra onde você vai sem se machucar.\n\nVocê escolhe trilha avançada olhando lei, corpo e biossegurança, não só hype de nome bonito.\n\nMatriz abaixo usa ids reais do campus THCProce; guarda isso como índice de vida.",
    body: [
      "OBJETIVO. Selecionar próximo módulo usando objetivo declarado, pré-requisitos e riscos típicos.",
      "MATRIZ DECISÓRIA (IDS DE CURSO NO MAPA).\n\n• Cultivo coberto / estufa — cultivo-greenhouse.\n\n• Campo aberto — cultivo-outdoor.\n\n• Sala fechada LED — cultivo-indoor.\n\n• Pós-colheita — secagem-cura.\n\n• Hash ice/rosin — extracoes-solventless.\n\n• Óleos e solventes (ciência + ética + segurança) — extracao-oleo.\n\n• Bancada analítica — laboratorio.\n\n• Medicina aprofundada — medicina.\n\n• Cozinha infundida — culinaria.\n\n• Genética — genetica.\n\n• Direito e políticas — legislacao.\n\n• Cooperativas — cooperativismo.\n\n• Indústria e carreira — industria.",
      "PREPARAÇÃO FÍSICA GENÉRICA. Área ventilada para aromas fortes; kit EPI básico (luvas nitrílicas, óculos, máscara PFF2 para poeiras se política permitir) antes mesmo de aulas teóricas de extração.",
      "PASSO A PASSO — escolha de carreira.\n\n1. Declare objetivo: pesquisa agronômica licenciada, apoio a paciente, comunicação científica, extração industrial.\n\n2. Liste lacunas (matemática de solução nutritiva, bioestatística, ética).\n\n3. Escolha uma trilha principal e uma paralela leve para manter base.",
      "RISCOS SEM FORMAÇÃO ADICIONAL. Solventes hidrocarbonetos — incêndio; comunicação de doses sem contexto — responsabilidade ética; consultoria sem atualizar portarias — multa a cliente.",
      "REVISÃO. Antes de indoor/outdoor, releia checklist da aula da planta e quiz da aula de COA — coerência técnica.",
      "SÍNTESE. Curiosidade madura evita acidente previsível; retorno periódico ao 101 mantém ética.",
      FOOTNOTE_MATERIALS
    ].join("\n\n"),
    objectives: [
      "Selecionar trilha alinhada a objetivo declarado citando ao menos dois ids de curso do mapa.",
      "Reconhecer riscos específicos de extração e cultivo sem formação complementar.",
      "Planejar revisão periódica do Cannabis 101 como âncora ética."
    ],
    closingSummary:
      "Escolha um id de curso da matriz, um manual oficial ou livro-texto para 30 dias e um lembrete na agenda — compromisso público consigo.",
    quiz: [
      q(
        "Antes de extração com solvente industrial:",
        0,
        "Curso específico de segurança química e ambiente legalmente adequado — não improvisação doméstica",
        "Ventilar cozinha aberta é suficiente sempre",
        "YouTube substitui CREA",
        "ETILENO improvisado em garrafa PET é ok"
      ),
      q(
        "Cultivo profissional demanda:",
        3,
        "Só paixão",
        "Ignorar diários ambientais",
        "Evitar NR por ser chata",
        "Registro de variáveis ambientais, lei local e segurança elétrica"
      ),
      q(
        "Melhor uso futuro deste 101:",
        1,
        "Encadernar e esquecer",
        "Reconsultar quando ensinar iniciantes ou atualizar políticas internas",
        "Substituir mestrado",
        "Converter-se em consultoria clandestina"
      )
    ],
    professorNotes:
      "Roadmap visual do campus; coordenadores das salas fazem pitch de 90 s cada.",
    media: MEDIA_INTRO,
    pedagogy: {
      practicalObjectiveLead: "Escolher próximo curso com objetivo escrito, pré-requisito e risco declarados.",
      practicalExplanation:
        "Matriz rápida no mapa: cultivo coberto/estufa (`cultivo-greenhouse`); campo (`cultivo-outdoor`); indoor LED (`cultivo-indoor`); pós-colheita (`secagem-cura`); solventless (`extracoes-solventless`); óleos e solventes (`extracao-oleo`); bancada (`laboratorio`); medicina (`medicina`); cozinha (`culinaria`); genética (`genetica`); legislação (`legislacao`); cooperativismo (`cooperativismo`); indústria (`industria`).\n\nVentilação pra aroma forte e EPI básico (luva nitrílica, óculos, máscara PFF2 pra poeira se política permitir) vêm antes até de teoria pesada de extração.",
      stepByStep: [
        "Escreve objetivo em uma linha — pesquisa agronômica licenciada, apoio a paciente, ciência, extração industrial.",
        "Lista lacuna técnica — nutrição de solução, bioestatística, ética — antes de se matricular em tudo ao mesmo tempo.",
        "Escolhe uma trilha principal e uma paralela leve pra não perder base.",
        "Antes de indoor/outdoor pesado, releia planta + COA deste 101 — coerência evita buraco técnico.",
        "Sem formação extra: solvente hidrocarboneto vira incêndio; dose sem contexto vira ética; consultoria sem atualizar portaria vira multa pro cliente."
      ],
      realExample:
        "Quem pula 101 e vai direto pra solvente improvisado arrisca fogo e sanção; quem volta ao 101 como âncora atualiza ética quando lei muda.",
      commonMistakes:
        "Achar que paixão substitui NR e diário de ambiente. Confundir pitch de marketing com pré-requisito técnico.",
      professionalObservation:
        "Eu peço pros coordenadores darem pitch de 90 s cada — aluno ouve vocês humanos, não só lista em pdf.",
      operationalSummary:
        "Curiosidade madura evita acidente previsível; revisitar este 101 de tempos em tempos mantém o nariz no ético.",
      exercise:
        "Escolhe um id da matriz, um manual oficial ou livro-texto pros próximos 30 dias e coloca lembrete na agenda — compromisso visível contigo mesmo.",
      nextLessonBridge:
        "Volta pro mapa quando quiser; o 101 continua aqui como contrato técnico com você mesmo."
    }
  }
};
